name: Schiphol Takeoff

project:
  version: 2.0.5
  github: https://github.com/schipholgroup/takeoff

markdown: kramdown

collections:
  deployment-steps:
    output: true

links:
  header:
  - title: GitHub
    url: https://github.com/schipholgroup/takeoff
  footer:
  - title: GitHub
    url: https://github.com/schipholgroup/takeoff
  - title: Issues
    url: https://github.com/schipholgroup/takeoff/issues

ui:
  header:
    color1: "#080331"
    color2: "#673051"
    trianglify: true

social:
  github:
    user: schipholgroup
    repo: takeoff
  twitter:
    enabled: false
    via:
    hash:
    account:
  facebook:
    enabled: false
    profileUrl:

# Build settings
exclude:
- Gemfile
- Gemfile.lock
- azure-pipelines.yml
- deployment.yml
- deploy.sh
- docker-compose-local.yml
- docker-compose.yml
- Dockerfile
- takeoff_config.yaml
- README.md
